spring:
  application:
    name: order-api
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:demo
    username:
    password:
    driverClassName: org.h2.Driver

app:
  jwt:
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG

# Jackson config
spring.jackson.default-property-inclusion: non_null
#spring.jackson.serialization.write-dates-as-timestamps: false
spring.jackson.date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

#spring.jackson.deserialization.fail-on-unknown-properties: true
#spring.jackson.deserialization.fail-on-missing-creator-properties: true
#spring.jackson.deserialization.fail-on-ignored-properties: true
